### ISSUE TITLE
Update package.json to use with later versions?

### ISSUE THREAD

**Issue by jamesjenner** [wix/react-native-navigation-bootstrap#2]
edited heavily: to clean up and just talk about the exact issue.

`package.json` has `2.0.0-experimental.116` as the version for react-native-navigation. This creates a problem as recently there was a change to the xcodeproj in ios, it was misnamed as ReactNativeController.xcodeproj. I had to manually update `package.json` so I could manually import the project inside xcode.

I know this was a bootstrap for 116, but could this be updated so it can be used for the current build of 2.0.0?

You could rightly argue that I shouldn't use the bootstrap, I should just install via npm. So feel free to close if my question is out of line.

On that, is it possible to setup the project for react-native-navigation-bootstrap so there is no need to drag in the xcodeproj, setup the path and so on? I suspect that the answer is no, but thought I would ask anyway. It's most prob. okay for xcode devs, but for others (like myself, it's a bit of a learning curve).

**Comment by gotters** [comment]
I am having the same issues.

Starting a new app (and I am still new to react-native) and would much rather start off with all the under the hood editing in place.
This was working for me but now the app just wont run.

Any suggestions?

**Comment by yedidyak** [comment]
Upgraded to latest React Native and latest Navigation
