### ISSUE TITLE
Forced to download sdk 25.0.1

### ISSUE THREAD

**Issue by MintyOwl** [wix/react-native-navigation-bootstrap#5]
Despite gradle build config set to sdk version ```23.0.1```, ```react-native run-android``` forcefully downloaded ```25.0.1```. Any idea why?

**Comment by chuyik** [comment]
@MintyOwl 
Nothing to do with this bootstrap, the dependency `react-native-navigation` use 25.0.1.

https://github.com/wix/react-native-navigation/blob/master/android/app/build.gradle#L50-L51

**Comment by MintyOwl** [comment]
Thanks
