### ISSUE TITLE
Where's the example code?

### ISSUE THREAD

**Issue by tmaly1980** [wix/react-native-navigation-bootstrap#7]
Based on the link from here: https://github.com/wix/react-native-navigation

It sounds like this is an "example app". However, I see absolutely no javascript code pertaining to trying out the navigation. It seems to merely be a starter project (ie react-native create app) with the dependencies included, and nothing more. What purpose does this repo serve?  

"If you prefer to learn more about the library and the APIs through code" <-- how? where? what code? I'm somewhat expecting a kitchen sink/demo app from what's mentioned there.

**Comment by awreese** [comment]
Agreed that this "demo" is a bit lacking, but if you take a look in either of the android or iOS index js files you'll find the normal default RN app rendered into a single screen app navigation component.  Not very useful for demoing what navigating between screens is actually about.

![image](https://user-images.githubusercontent.com/17777797/28086104-b6a63bc2-6632-11e7-9dfd-db44249d6108.png)

**Comment by MrLoh** [comment]
I'm also very confused. Where can one find the example code of the example app that the gif is showing in the main repo. This project looks really good, but the documentation is far to limited to use without a real code example.

**Comment by DanielZlotin** [comment]
This is not an example app for navigation, it exists just to help users bootstrap the navigation into a new clean app
